%% MIR Feature Extraction for NHS2 audio snippets

% get files names
folder = "NHS2_FINAL/corpus_raw/";
dr = dir(folder)
names = {dr.name}
just_names = regexp(names,".*(?=\.mp3)",'match')

num_files = length(just_names);

% init feature table
ft_type = [ ...
    "string", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    "double", ...
    %"double", ...
    %"double", ...
    %"double", ...
    %"double", ...
    %"double", ...
    %"double", ...
    ];
ft_name = [ ...
    "song", ...
    "ex_simple_lowenergy_mean", ...
    "ex_simple_brightness_mean", ...
    "ex_simple_roughness_mean", ...
    "ex_simple_centroid_mean", ...
    "ex_spectral_centroid_mean", ...
    "ex_spectral_centroid_std", ...
    "ex_spectral_brightness_mean", ...
    "ex_spectral_brightness_std", ...
    "ex_spectral_spread_mean", ...
    "ex_spectral_spread_std", ...
    "ex_spectral_skewness_mean", ...
    "ex_spectral_skewness_std", ...
    "ex_spectral_kurtosis_mean", ...
    "ex_spectral_kurtosis_std", ...
    "ex_spectral_rolloff95_mean", ...
    "ex_spectral_rolloff95_std", ...
    "ex_spectral_rolloff85_mean", ...
    "ex_spectral_rolloff85_std", ...
    "ex_spectral_spectenropy_mean", ...
    "ex_spectral_spectenropy_std", ...
    "ex_spectral_flatness_mean", ...
    "ex_spectral_flatness_std", ...
    "ex_spectral_roughness_mean", ...
    "ex_spectral_roughness_std", ...
    "ex_spectral_irregularity_mean", ...
    "ex_spectral_irregularity_std", ...
    "ex_tonal_keyclarity_mean", ...
    "ex_tonal_keyclarity_std", ...
    "ex_tonal_mode_mean", ...
    "ex_tonal_mode_std", ...
    "ex_rhythm_tempo_mean", ...
    "ex_rhythm_tempo_std", ...
    "ex_rhythm_attack_time_mean", ...
    "ex_rhythm_attack_time_std", ...
    "ex_rhythm_attack_slope_mean", ...
    "ex_rhythm_attack_slope_std", ...
    "ex_dynamics_rms_mean", ...
    "ex_dynamics_rms_std", ...
    %"ex_spectral_mfcc_mean", ...
    %"ex_spectral_mfcc_std", ...
    %"ex_spectral_dmfcc_mean", ...
    %"ex_spectral_ddmfcc_mean", ...
    %"ex_mel_subband_amplitude_mean", ...
    %"ex_mel_subband_amplitude_std" ...
    ];
num_features = length(ft_name);

feature_table = table( ...
    'Size',[num_files, num_features], ...
    'VariableNames',ft_name, ...
    'VariableTypes', ft_type ...
    );

%% Run Feature Extraction

for af = 1:num_files
    if isempty(just_names{af})
        continue
    end

    % get song name
    % file_nm = split(audio_files{af},'/');
    % song_nm = split(file_nm{2},'.'); 
    % song = song_nm{1}
    song = just_names{af}{1};
    afile = char(folder + song + ".mp3")
    
    smp_le = mirlowenergy(afile); % simple low energy
    smp_b = mirbrightness(afile); % simple brightness 
    smp_r = mirroughness(afile); % simple roughness (mean)
    smp_c = mircentroid(afile); % simple centroid
    feats = mirfeatures(afile, 'Stat');

    features = {song, mirgetdata(smp_le), mirgetdata(smp_b), ... % simple
        mean(mirgetdata(smp_r)),mirgetdata(smp_c), ...
        feats.spectral.centroid.Mean, feats.spectral.centroid.Std, ... % spectral
        feats.spectral.brightness.Mean, feats.spectral.brightness.Std, ...
        feats.spectral.spread.Mean, feats.spectral.spread.Std, ...
        feats.spectral.skewness.Mean, feats.spectral.skewness.Std, ...
        feats.spectral.kurtosis.Mean, feats.spectral.kurtosis.Std, ...
        feats.spectral.rolloff95.Mean, feats.spectral.rolloff95.Std, ...
        feats.spectral.rolloff85.Mean, feats.spectral.rolloff85.Std, ...
        feats.spectral.spectentropy.Mean, feats.spectral.spectentropy.Std, ...
        feats.spectral.flatness.Mean, feats.spectral.flatness.Std, ...
        feats.spectral.roughness.Mean, feats.spectral.roughness.Std, ...
        feats.spectral.irregularity.Mean, feats.spectral.irregularity.Std, ...
        feats.tonal.keyclarity.Mean, feats.tonal.keyclarity.Std, ... % tonal
        feats.tonal.mode.Mean, feats.tonal.mode.Std, ...
        feats.rhythm.tempo.Mean, feats.rhythm.tempo.Std, ... % rhythm
        feats.rhythm.attack.time.Mean, feats.rhythm.attack.time.Std, ...
        feats.rhythm.attack.slope.Mean, feats.rhythm.attack.slope.Std, ...
        feats.dynamics.rms.Mean, feats.dynamics.rms.Std, ...
        };
    feature_table(af,:) = features;
end

save("audioExtraction","feature_table")

%% add simple brightness (oops, fixed above)


for af = 1:num_files
    if isempty(just_names{af})
        continue
    end
    song = just_names{af}{1};
    afile = char(folder + song + ".mp3")

    smp_b = mirbrightness(afile); % simple brightness 
    feature_table{af,3} = mirgetdata(smp_b);
end

save("audioExtraction","feature_table")
